import { useState } from "react";
import React from 'react'
import Table from "react-bootstrap/Table";
const genesOriginal = [{ "value": "APOE", "label": "APOE" }, { "value": "CDH1", "label": "CDH1" }, { "value": "SERPINA1", "label": "SERPINA1" }, { "value": "IL12B", "label": "IL12B" },
{ "value": "GC", "label": "GC" }, { "value": "TF", "label": "TF" }, { "value": "SERPINC1", "label": "SERPINC1" }, { "value": "SAA!", "label": "SAA!" }, { "value": "VTN", "label": "VTN" }, { "value": "SERPINA3", "label": "SERPINA3" }, { "value": "PI3", "label": "PI3" }, { "value": "FETUB", "label": "FETUB" }, { "value": "IL6", "label": "IL6" }, { "value": "AQP1", "label": "AQP1" }, { "value": "TGFB1", "label": "TGFB1" }, { "value": "TP53", "label": "TP53" }, { "value": "DNASE1", "label": "DNASE1" }, { "value": "MMP9", "label": "MMP9" }, { "value": "EGFR", "label": "EGFR" }, { "value": "CDKN2A", "label": "CDKN2A" }, { "value": "CXCL8", "label": "CXCL8" }, { "value": "TERT", "label": "TERT" }, { "value": "VEGFA", "label": "VEGFA" }, { "value": "CRP", "label": "CRP" }, { "value": "KRAS", "label": "KRAS" }, { "value": "CCL22", "label": "CCL22" }, { "value": "C9orf72", "label": "C9orf72" }, { "value": "KLK3", "label": "KLK3" }, { "value": "BCL2", "label": "BCL2" }, { "value": "BRAF", "label": "BRAF" }, { "value": "IL1B", "label": "IL1B" }, { "value": "ADIPOQ", "label": "ADIPOQ" }, { "value": "ICAM1", "label": "ICAM1" }, { "value": "DRD2", "label": "DRD2" }, { "value": "LRRK2", "label": "LRRK2" }, { "value": "SPP1", "label": "SPP1" }, { "value": "BCKDHB", "label": "BCKDHB" }, { "value": "MMP2", "label": "MMP2" }, { "value": "GSTP1", "label": "GSTP1" }, { "value": "PIK3CA", "label": "PIK3CA" }, { "value": "BDN", "label": "BDN" }, { "value": "LCN2", "label": "LCN2" }, { "value": "F2", "label": "F2" }, { "value": "MLH1", "label": "MLH1" }, { "value": "TIMP1", "label": "TIMP1" }, { "value": "CD44", "label": "CD44" },
{ "value": "HMGB1", "label": "HMGB1" }, { "value": "BIRC5", "label": "BIRC5" }, { "value": "NOS3", "label": "NOS3" }, { "value": "EDN1", "label": "EDN1" }, { "value": "APOA1", "label": "APOA1" }, { "value": "MTHFR", "label": "MTHFR" }, { "value": "CST3", "label": "CST3" }, { "value": "RB1", "label": "RB1" }, { "value": "ALK", "label": "ALK" }, { "value": "S100B", "label": "S100B" }, { "value": "C3", "label": "C3" }, { "value": "LEP", "label": "LEP" }, { "value": "RAC1", "label": "RAC1" }, { "value": "DMD", "label": "DMD" }, { "value": "HSPB1", "label": "HSPB1" }, { "value": "IL18", "label": "IL18" }, { "value": "NPPB", "label": "NPPB" }, { "value": "VDR", "label": "VDR" }, { "value": "HFE", "label": "HFE" }, { "value": "HP", "label": "HP" }, { "value": "EGF", "label": "EGF" }, { "value": "FLT1", "label": "FLT1" }, { "value": "PLG", "label": "PLG" }, { "value": "HMOX1", "label": "HMOX1" }, { "value": "APC", "label": "APC" }, { "value": "TOP2A", "label": "TOP2A" }, { "value": "PLAU", "label": "PLAU" }, { "value": "IL17A", "label": "IL17A" }, { "value": "ALB", "label": "ALB" }, { "value": "FGFR3", "label": "FGFR3" }, { "value": "MPO", "label": "MPO" }, { "value": "VIM", "label": "VIM" }, { "value": "ERG", "label": "ERG" }, { "value": "TWIST1", "label": "TWIST1" }, { "value": "S100A4", "label": "S100A4" }, { "value": "PLAUR", "label": "PLAUR" }, { "value": "TTN", "label": "TTN" }, { "value": "CXCL10", "label": "CXCL10" }, {
    "value": "SLC4A1", "label":
        "SLC4A1"
}, { "value": "PKD1", "label": "PKD1" }, { "value": "VCAM1", "label": "VCAM1" }, { "value": "TIMP2", "label": "TIMP2" }, { "value": "CYP2D6", "label": "CYP2D6" }, { "value": "COL1A1", "label": "COL1A1" }, { "value": "CYP3A4", "label": "CYP3A4" }, { "value": "MIF", "label": "MIF" }, { "value": "BSG", "label": "BSG" }, { "value": "CHI3L1", "label": "CHI3L1" }, { "value": "TNFRSF11B", "label": "TNFRSF11B" }, { "value": "GRN", "label": "GRN" }, { "value": "FOXP3", "label": "FOXP3" }, { "value": "HAMP", "label": "HAMP" }, { "value": "FGFR2", "label": "FGFR2" }, { "value": "PLK1", "label": "PLK1" }, { "value": "RASSF1", "label": "RASSF1" }, { "value": "AGT", "label": "AGT" }, { "value": "PRDX1", "label": "PRDX1" }, { "value": "DAPK1", "label": "DAPK1" }, { "value": "HMGA1", "label": "HMGA1" }, { "value": "POSTN", "label": "POSTN" }, { "value": "LEPR", "label": "LEPR" }, { "value": "ADM", "label": "ADM" }, { "value": "FGF23", "label": "FGF23" }, { "value": "CASR", "label": "CASR" }, { "value": "ENG", "label": "ENG" }, { "value": "SHC1", "label": "SHC1" }, { "value": "CA9", "label": "CA9" }, { "value": "MCM2", "label": "MCM2" }, { "value": "GNAI2", "label": "GNAI2" }, { "value": "HAVCR2", "label": "HAVCR2" }, { "value": "ZEB1", "label": "ZEB1" }, { "value": "AFP", "label": "AFP" }, { "value": "B2M", "label": "B2M" }, { "value": "CD59", "label": "CD59" }, { "value": "KLRK1", "label": "KLRK1" }, { "value": "PKD2", "label": "PKD2" }, { "value": "YWHAQ", "label": "YWHAQ" }, { "value": "DMBT1", "label": "DMBT1" }, { "value": "INHBA", "label": "INHBA" }, { "value": "HAVCR1", "label": "HAVCR1" }, { "value": "CD40LG", "label": "CD40LG" }, { "value": "CYP1A2", "label": "CYP1A2" }, { "value": "NGF", "label": "NGF" }, { "value": "IDO1", "label": "IDO1" }, { "value": "CAMP", "label": "CAMP" }, { "value": "LRP2", "label": "LRP2" }, { "value": "TGFBI", "label": "TGFBI" }, { "value": "MEFV", "label": "MEFV" }, { "value": "FTL", "label": "FTL" }, { "value": "PDGFB", "label": "PDGFB" }, { "value": "KLK2", "label": "KLK2" }, { "value": "KNG1", "label": "KNG1" }, { "value": "COL2A1", "label": "COL2A1" },
{ "value": "HPSE", "label": "HPSE" }, { "value": "COL4A1", "label": "COL4A1" }, { "value": "ANGPTL4", "label": "ANGPTL4" }, { "value": "ACHE", "label": "ACHE" }, { "value": "F2R", "label": "F2R" }, { "value": "ANGPT2", "label": "ANGPT2" }, { "value": "AMBP", "label": "AMBP" }, { "value": "MME", "label": "MME" }, { "value": "EDNRB", "label": "EDNRB" }, { "value": "KL", "label": "KL" }, { "value": "YWHAB", "label": "YWHAB" }, { "value": "ADRB1", "label": "ADRB1" }, { "value": "CTNND1", "label": "CTNND1" }, { "value": "PGF", "label": "PGF" }, { "value": "AQP5", "label": "AQP5" }, { "value": "NPHS1", "label": "NPHS1" }, { "value": "AQP2", "label": "AQP2" }, { "value": "PDIA3", "label": "PDIA3" }, { "value": "POLG", "label": "POLG" }, { "value": "S100A1", "label": "S100A1" }, { "value": "FGF21", "label": "FGF21" }, { "value": "COL18A1", "label": "COL18A1" }, { "value": "AKR1B1", "label": "AKR1B1" }, { "value": "MMP8", "label": "MMP8" }, { "value": "ADRB3", "label": "ADRB3" }, { "value": "IL23A", "label": "IL23A" }, { "value": "SLC7A9", "label": "SLC7A9" }, { "value": "NTN1", "label": "NTN1" }, { "value": "CP", "label": "CP" }, { "value": "CUBN", "label": "CUBN" }, { "value": "AGR2", "label": "AGR2" }, { "value": "CXCL1", "label": "CXCL1" }, { "value": "AVPR2", "label": "AVPR2" }, {
    "value":
        "CYP2A6", "label": "CYP2A6"
}, { "value": "TNC", "label": "TNC" }, { "value": "IDH2", "label": "IDH2" }, { "value": "RNLS", "label": "RNLS" }, {
    "value": "TREM1",
    "label": "TREM1"
}, { "value": "CX3CL1", "label": "CX3CL1" }, { "value": "GLA", "label": "GLA" }, { "value": "MTRR", "label": "MTRR" }, {
    "value": "POR", "label":
        "POR"
}, { "value": "PPOX", "label": "PPOX" }, { "value": "UBQLN2", "label": "UBQLN2" }, { "value": "DEK", "label": "DEK" }, { "value": "PAX8", "label": "PAX8" }, { "value": "TFF3", "label": "TFF3" }, { "value": "TFF1", "label": "TFF1" }, { "value": "AZGP1", "label": "AZGP1" }, { "value": "ENO1", "label": "ENO1" }, {
    "value":
        "HMBS", "label": "HMBS"
}, { "value": "MSTN", "label": "MSTN" }, { "value": "IGF2R", "label": "IGF2R" }, { "value": "PSAP", "label": "PSAP" }, { "value": "AQP7", "label": "AQP7" }, { "value": "NUMA1", "label": "NUMA1" }, { "value": "CGA", "label": "CGA" }, { "value": "GSTO2", "label": "GSTO2" }, {
    "value": "FABP1", "label":
        "FABP1"
}, { "value": "TNFSF12", "label": "TNFSF12" }, { "value": "IFNGR1", "label": "IFNGR1" }, { "value": "SDHA", "label": "SDHA" }, { "value": "XDH", "label": "XDH" }, { "value": "CD80", "label": "CD80" }, { "value": "ALCAM", "label": "ALCAM" }, { "value": "CXCL5", "label": "CXCL5" }, { "value": "HGD", "label": "HGD" }, { "value": "TRPV5", "label": "TRPV5" }, { "value": "ROBO2", "label": "ROBO2" }, { "value": "HCFC1", "label": "HCFC1" }, { "value": "APOM", "label": "APOM" }, { "value": "REG1A", "label": "REG1A" }, { "value": "CAD", "label": "CAD" }, { "value": "ORM1", "label": "ORM1" }, { "value": "SCNN1G", "label": "SCNN1G" }, { "value": "FBP1", "label": "FBP1" }, { "value": "ETS2", "label": "ETS2" }, { "value": "SNAP23", "label": "SNAP23" }, { "value": "CIB1", "label": "CIB1" }, { "value": "UROD", "label": "UROD" }, { "value": "RGN", "label": "RGN" }, { "value": "ANXA3", "label": "ANXA3" }, { "value": "RNASE2", "label": "RNASE2" }, {
    "value": "ACADS", "label":
        "ACADS"
}, { "value": "BTC", "label": "BTC" }, { "value": "MMACHC", "label": "MMACHC" }, { "value": "ALDH5A1", "label": "ALDH5A1" }, { "value": "ACY1", "label": "ACY1" }, { "value": "TAGLN2", "label": "TAGLN2" }, { "value": "CLASP2", "label": "CLASP2" }, { "value": "ASL", "label": "ASL" }, { "value": "DPYS", "label": "DPYS" }, { "value": "ABCD4", "label": "ABCD4" }, { "value": "HOGA1", "label": "HOGA1" }, { "value": "UCN3", "label": "UCN3" }, { "value": "CPA3", "label": "CPA3" }, { "value": "RHCG", "label": "RHCG" }, { "value": "MMADHC", "label": "MMADHC" }, { "value": "N6AMT1", "label": "N6AMT1" }, { "value": "CDKN1A", "label": "CDKN1A" }, { "value": "MKI67", "label": "MKI67" }, { "value": "CDKN1B", "label": "CDKN1B" }, { "value": "LCP1", "label": "LCP1" }, { "value": "HIF1A", "label": "HIF1A" }, { "value": "PPARG", "label": "PPARG" }, { "value": "CXCL12", "label": "CXCL12" }, { "value": "FN1", "label": "FN1" }, { "value": "RUNX1", "label": "RUNX1" }, { "value": "HRAS", "label": "HRAS" }, { "value": "EZR", "label": "EZR" }, { "value": "NRAS", "label": "NRAS" }, { "value": "ATG16L1", "label": "ATG16L1" }, { "value": "PRKACA", "label": "PRKACA" }, { "value": "ITGB2", "label": "ITGB2" }, { "value": "MSN", "label": "MSN" }, { "value": "U2AF2", "label": "U2AF2" }, { "value": "ATXN2", "label": "ATXN2" }, { "value": "SIRT7", "label": "SIRT7" }, { "value": "HERC2", "label": "HERC2" }, { "value": "SLPI", "label": "SLPI" }, { "value": "PLS3", "label": "PLS3" }, { "value": "RAD23B", "label": "RAD23B" }, { "value": "NR2C2", "label": "NR2C2" }, { "value": "RNF41", "label": "RNF41" }, { "value": "AIF1", "label": "AIF1" }, { "value": "HEXIM1", "label": "HEXIM1" }, { "value": "DPF2", "label": "DPF2" }, { "value": "GLYR1", "label": "GLYR1" }, { "value": "MED23", "label": "MED23" }, { "value": "DDX19B", "label": "DDX19B" }, { "value": "BICD2", "label": "BICD2" }, { "value": "PPME1", "label": "PPME1" }, { "value": "PLEKHA4", "label": "PLEKHA4" }, { "value": "SERPINC", "label": "SERPINC" }]
const GeneNames = (props) => {
    const [genes, setGenes] = React.useState([{ "value": "APOE", "label": "APOE" }, { "value": "CDH1", "label": "CDH1" }, { "value": "SERPINA1", "label": "SERPINA1" }, { "value": "IL12B", "label": "IL12B" },
    { "value": "GC", "label": "GC" }, { "value": "TF", "label": "TF" }, { "value": "SERPINC1", "label": "SERPINC1" }, { "value": "SAA!", "label": "SAA!" }, { "value": "VTN", "label": "VTN" }, { "value": "SERPINA3", "label": "SERPINA3" }, { "value": "PI3", "label": "PI3" }, { "value": "FETUB", "label": "FETUB" }, { "value": "IL6", "label": "IL6" }, { "value": "AQP1", "label": "AQP1" }, { "value": "TGFB1", "label": "TGFB1" }, { "value": "TP53", "label": "TP53" }, { "value": "DNASE1", "label": "DNASE1" }, { "value": "MMP9", "label": "MMP9" }, { "value": "EGFR", "label": "EGFR" }, { "value": "CDKN2A", "label": "CDKN2A" }, { "value": "CXCL8", "label": "CXCL8" }, { "value": "TERT", "label": "TERT" }, { "value": "VEGFA", "label": "VEGFA" }, { "value": "CRP", "label": "CRP" }, { "value": "KRAS", "label": "KRAS" }, { "value": "CCL22", "label": "CCL22" }, { "value": "C9orf72", "label": "C9orf72" }, { "value": "KLK3", "label": "KLK3" }, { "value": "BCL2", "label": "BCL2" }, { "value": "BRAF", "label": "BRAF" }, { "value": "IL1B", "label": "IL1B" }, { "value": "ADIPOQ", "label": "ADIPOQ" }, { "value": "ICAM1", "label": "ICAM1" }, { "value": "DRD2", "label": "DRD2" }, { "value": "LRRK2", "label": "LRRK2" }, { "value": "SPP1", "label": "SPP1" }, { "value": "BCKDHB", "label": "BCKDHB" }, { "value": "MMP2", "label": "MMP2" }, { "value": "GSTP1", "label": "GSTP1" }, { "value": "PIK3CA", "label": "PIK3CA" }, { "value": "BDN", "label": "BDN" }, { "value": "LCN2", "label": "LCN2" }, { "value": "F2", "label": "F2" }, { "value": "MLH1", "label": "MLH1" }, { "value": "TIMP1", "label": "TIMP1" }, { "value": "CD44", "label": "CD44" },
    { "value": "HMGB1", "label": "HMGB1" }, { "value": "BIRC5", "label": "BIRC5" }, { "value": "NOS3", "label": "NOS3" }, { "value": "EDN1", "label": "EDN1" }, { "value": "APOA1", "label": "APOA1" }, { "value": "MTHFR", "label": "MTHFR" }, { "value": "CST3", "label": "CST3" }, { "value": "RB1", "label": "RB1" }, { "value": "ALK", "label": "ALK" }, { "value": "S100B", "label": "S100B" }, { "value": "C3", "label": "C3" }, { "value": "LEP", "label": "LEP" }, { "value": "RAC1", "label": "RAC1" }, { "value": "DMD", "label": "DMD" }, { "value": "HSPB1", "label": "HSPB1" }, { "value": "IL18", "label": "IL18" }, { "value": "NPPB", "label": "NPPB" }, { "value": "VDR", "label": "VDR" }, { "value": "HFE", "label": "HFE" }, { "value": "HP", "label": "HP" }, { "value": "EGF", "label": "EGF" }, { "value": "FLT1", "label": "FLT1" }, { "value": "PLG", "label": "PLG" }, { "value": "HMOX1", "label": "HMOX1" }, { "value": "APC", "label": "APC" }, { "value": "TOP2A", "label": "TOP2A" }, { "value": "PLAU", "label": "PLAU" }, { "value": "IL17A", "label": "IL17A" }, { "value": "ALB", "label": "ALB" }, { "value": "FGFR3", "label": "FGFR3" }, { "value": "MPO", "label": "MPO" }, { "value": "VIM", "label": "VIM" }, { "value": "ERG", "label": "ERG" }, { "value": "TWIST1", "label": "TWIST1" }, { "value": "S100A4", "label": "S100A4" }, { "value": "PLAUR", "label": "PLAUR" }, { "value": "TTN", "label": "TTN" }, { "value": "CXCL10", "label": "CXCL10" }, {
        "value": "SLC4A1", "label":
            "SLC4A1"
    }, { "value": "PKD1", "label": "PKD1" }, { "value": "VCAM1", "label": "VCAM1" }, { "value": "TIMP2", "label": "TIMP2" }, { "value": "CYP2D6", "label": "CYP2D6" }, { "value": "COL1A1", "label": "COL1A1" }, { "value": "CYP3A4", "label": "CYP3A4" }, { "value": "MIF", "label": "MIF" }, { "value": "BSG", "label": "BSG" }, { "value": "CHI3L1", "label": "CHI3L1" }, { "value": "TNFRSF11B", "label": "TNFRSF11B" }, { "value": "GRN", "label": "GRN" }, { "value": "FOXP3", "label": "FOXP3" }, { "value": "HAMP", "label": "HAMP" }, { "value": "FGFR2", "label": "FGFR2" }, { "value": "PLK1", "label": "PLK1" }, { "value": "RASSF1", "label": "RASSF1" }, { "value": "AGT", "label": "AGT" }, { "value": "PRDX1", "label": "PRDX1" }, { "value": "DAPK1", "label": "DAPK1" }, { "value": "HMGA1", "label": "HMGA1" }, { "value": "POSTN", "label": "POSTN" }, { "value": "LEPR", "label": "LEPR" }, { "value": "ADM", "label": "ADM" }, { "value": "FGF23", "label": "FGF23" }, { "value": "CASR", "label": "CASR" }, { "value": "ENG", "label": "ENG" }, { "value": "SHC1", "label": "SHC1" }, { "value": "CA9", "label": "CA9" }, { "value": "MCM2", "label": "MCM2" }, { "value": "GNAI2", "label": "GNAI2" }, { "value": "HAVCR2", "label": "HAVCR2" }, { "value": "ZEB1", "label": "ZEB1" }, { "value": "AFP", "label": "AFP" }, { "value": "B2M", "label": "B2M" }, { "value": "CD59", "label": "CD59" }, { "value": "KLRK1", "label": "KLRK1" }, { "value": "PKD2", "label": "PKD2" }, { "value": "YWHAQ", "label": "YWHAQ" }, { "value": "DMBT1", "label": "DMBT1" }, { "value": "INHBA", "label": "INHBA" }, { "value": "HAVCR1", "label": "HAVCR1" }, { "value": "CD40LG", "label": "CD40LG" }, { "value": "CYP1A2", "label": "CYP1A2" }, { "value": "NGF", "label": "NGF" }, { "value": "IDO1", "label": "IDO1" }, { "value": "CAMP", "label": "CAMP" }, { "value": "LRP2", "label": "LRP2" }, { "value": "TGFBI", "label": "TGFBI" }, { "value": "MEFV", "label": "MEFV" }, { "value": "FTL", "label": "FTL" }, { "value": "PDGFB", "label": "PDGFB" }, { "value": "KLK2", "label": "KLK2" }, { "value": "KNG1", "label": "KNG1" }, { "value": "COL2A1", "label": "COL2A1" },
    { "value": "HPSE", "label": "HPSE" }, { "value": "COL4A1", "label": "COL4A1" }, { "value": "ANGPTL4", "label": "ANGPTL4" }, { "value": "ACHE", "label": "ACHE" }, { "value": "F2R", "label": "F2R" }, { "value": "ANGPT2", "label": "ANGPT2" }, { "value": "AMBP", "label": "AMBP" }, { "value": "MME", "label": "MME" }, { "value": "EDNRB", "label": "EDNRB" }, { "value": "KL", "label": "KL" }, { "value": "YWHAB", "label": "YWHAB" }, { "value": "ADRB1", "label": "ADRB1" }, { "value": "CTNND1", "label": "CTNND1" }, { "value": "PGF", "label": "PGF" }, { "value": "AQP5", "label": "AQP5" }, { "value": "NPHS1", "label": "NPHS1" }, { "value": "AQP2", "label": "AQP2" }, { "value": "PDIA3", "label": "PDIA3" }, { "value": "POLG", "label": "POLG" }, { "value": "S100A1", "label": "S100A1" }, { "value": "FGF21", "label": "FGF21" }, { "value": "COL18A1", "label": "COL18A1" }, { "value": "AKR1B1", "label": "AKR1B1" }, { "value": "MMP8", "label": "MMP8" }, { "value": "ADRB3", "label": "ADRB3" }, { "value": "IL23A", "label": "IL23A" }, { "value": "SLC7A9", "label": "SLC7A9" }, { "value": "NTN1", "label": "NTN1" }, { "value": "CP", "label": "CP" }, { "value": "CUBN", "label": "CUBN" }, { "value": "AGR2", "label": "AGR2" }, { "value": "CXCL1", "label": "CXCL1" }, { "value": "AVPR2", "label": "AVPR2" }, {
        "value":
            "CYP2A6", "label": "CYP2A6"
    }, { "value": "TNC", "label": "TNC" }, { "value": "IDH2", "label": "IDH2" }, { "value": "RNLS", "label": "RNLS" }, {
        "value": "TREM1",
        "label": "TREM1"
    }, { "value": "CX3CL1", "label": "CX3CL1" }, { "value": "GLA", "label": "GLA" }, { "value": "MTRR", "label": "MTRR" }, {
        "value": "POR", "label":
            "POR"
    }, { "value": "PPOX", "label": "PPOX" }, { "value": "UBQLN2", "label": "UBQLN2" }, { "value": "DEK", "label": "DEK" }, { "value": "PAX8", "label": "PAX8" }, { "value": "TFF3", "label": "TFF3" }, { "value": "TFF1", "label": "TFF1" }, { "value": "AZGP1", "label": "AZGP1" }, { "value": "ENO1", "label": "ENO1" }, {
        "value":
            "HMBS", "label": "HMBS"
    }, { "value": "MSTN", "label": "MSTN" }, { "value": "IGF2R", "label": "IGF2R" }, { "value": "PSAP", "label": "PSAP" }, { "value": "AQP7", "label": "AQP7" }, { "value": "NUMA1", "label": "NUMA1" }, { "value": "CGA", "label": "CGA" }, { "value": "GSTO2", "label": "GSTO2" }, {
        "value": "FABP1", "label":
            "FABP1"
    }, { "value": "TNFSF12", "label": "TNFSF12" }, { "value": "IFNGR1", "label": "IFNGR1" }, { "value": "SDHA", "label": "SDHA" }, { "value": "XDH", "label": "XDH" }, { "value": "CD80", "label": "CD80" }, { "value": "ALCAM", "label": "ALCAM" }, { "value": "CXCL5", "label": "CXCL5" }, { "value": "HGD", "label": "HGD" }, { "value": "TRPV5", "label": "TRPV5" }, { "value": "ROBO2", "label": "ROBO2" }, { "value": "HCFC1", "label": "HCFC1" }, { "value": "APOM", "label": "APOM" }, { "value": "REG1A", "label": "REG1A" }, { "value": "CAD", "label": "CAD" }, { "value": "ORM1", "label": "ORM1" }, { "value": "SCNN1G", "label": "SCNN1G" }, { "value": "FBP1", "label": "FBP1" }, { "value": "ETS2", "label": "ETS2" }, { "value": "SNAP23", "label": "SNAP23" }, { "value": "CIB1", "label": "CIB1" }, { "value": "UROD", "label": "UROD" }, { "value": "RGN", "label": "RGN" }, { "value": "ANXA3", "label": "ANXA3" }, { "value": "RNASE2", "label": "RNASE2" }, {
        "value": "ACADS", "label":
            "ACADS"
    }, { "value": "BTC", "label": "BTC" }, { "value": "MMACHC", "label": "MMACHC" }, { "value": "ALDH5A1", "label": "ALDH5A1" }, { "value": "ACY1", "label": "ACY1" }, { "value": "TAGLN2", "label": "TAGLN2" }, { "value": "CLASP2", "label": "CLASP2" }, { "value": "ASL", "label": "ASL" }, { "value": "DPYS", "label": "DPYS" }, { "value": "ABCD4", "label": "ABCD4" }, { "value": "HOGA1", "label": "HOGA1" }, { "value": "UCN3", "label": "UCN3" }, { "value": "CPA3", "label": "CPA3" }, { "value": "RHCG", "label": "RHCG" }, { "value": "MMADHC", "label": "MMADHC" }, { "value": "N6AMT1", "label": "N6AMT1" }, { "value": "CDKN1A", "label": "CDKN1A" }, { "value": "MKI67", "label": "MKI67" }, { "value": "CDKN1B", "label": "CDKN1B" }, { "value": "LCP1", "label": "LCP1" }, { "value": "HIF1A", "label": "HIF1A" }, { "value": "PPARG", "label": "PPARG" }, { "value": "CXCL12", "label": "CXCL12" }, { "value": "FN1", "label": "FN1" }, { "value": "RUNX1", "label": "RUNX1" }, { "value": "HRAS", "label": "HRAS" }, { "value": "EZR", "label": "EZR" }, { "value": "NRAS", "label": "NRAS" }, { "value": "ATG16L1", "label": "ATG16L1" }, { "value": "PRKACA", "label": "PRKACA" }, { "value": "ITGB2", "label": "ITGB2" }, { "value": "MSN", "label": "MSN" }, { "value": "U2AF2", "label": "U2AF2" }, { "value": "ATXN2", "label": "ATXN2" }, { "value": "SIRT7", "label": "SIRT7" }, { "value": "HERC2", "label": "HERC2" }, { "value": "SLPI", "label": "SLPI" }, { "value": "PLS3", "label": "PLS3" }, { "value": "RAD23B", "label": "RAD23B" }, { "value": "NR2C2", "label": "NR2C2" }, { "value": "RNF41", "label": "RNF41" }, { "value": "AIF1", "label": "AIF1" }, { "value": "HEXIM1", "label": "HEXIM1" }, { "value": "DPF2", "label": "DPF2" }, { "value": "GLYR1", "label": "GLYR1" }, { "value": "MED23", "label": "MED23" }, { "value": "DDX19B", "label": "DDX19B" }, { "value": "BICD2", "label": "BICD2" }, { "value": "PPME1", "label": "PPME1" }, { "value": "PLEKHA4", "label": "PLEKHA4" }, { "value": "SERPINC", "label": "SERPINC" }])
    return (
        <div className="py-4">
            <label style={{ color: 'black' }}>Search: <input type="text" onChange={(e) => { console.log(genes); e.target.value.length == 0 ? setGenes(genesOriginal) :setGenes(genes.filter((gene) => gene.value.startsWith(e.target.value) && e.target.value != 0)) }}></input></label>
            <Table striped bordered hover>
                <tbody>
                    <tr>
                        <th>Gene Name</th>
                    </tr>
                    {genes.map(item => <tr key={item.label}>
                        {item.value}
                    </tr>)}

                </tbody>
            </Table>
        </div>
    );
};
export default GeneNames;
