import { useState } from "react";
import React from 'react'
import Table from "react-bootstrap/Table";
const genesOriginal = [{ 'value': '1NFN', 'label': '1NFN' }, { 'value': '4ZT1', 'label': '4ZT1' }, { 'value': '6I7U', 'label': '6I7U' }, { 'value': '5MXA', 'label': '5MXA' }, {
    'value':
      '1KXP', 'label': '1KXP'
  }, { 'value': '3V83', 'label': '3V83' }, { 'value': '2GD4', 'label': '2GD4' }, { 'value': '4IP8', 'label': '4IP8' }, { 'value': '6O5E', 'label': '6O5E' }, { 'value': '1QMN', 'label': '1QMN' }, { 'value': '1FLE', 'label': '1FLE' }, { 'value': '6SAZ', 'label': '6SAZ' }, { 'value': '1ALU', 'label': '1ALU' }, { 'value': '4CSK', 'label': '4CSK' }, { 'value': '3KFD', 'label': '3KFD' }, { 'value': '2BIP', 'label': '2BIP' }, { 'value': '4AWN', 'label': '4AWN' }, { 'value': '1L6J', 'label': '1L6J' }, { 'value': '5XWD', 'label': '5XWD' }, { 'value': '1BI7', 'label': '1BI7' }, { 'value': '6N2U', 'label': '6N2U' }, {
    'value': '5UGW',
    'label': '5UGW'
  }, { 'value': '4GLN', 'label': '4GLN' }, { 'value': '3PVN', 'label': '3PVN' }, { 'value': '6GOD', 'label': '6GOD' }, { 'value': '1DOK', 'label': '1DOK' }, { 'value': '6V4U', 'label': '6V4U' }, { 'value': '2ZCH', 'label': '2ZCH' }, { 'value': '5VAU', 'label': '5VAU' }, { 'value': '5C9C', 'label': '5C9C' }, { 'value': '5R8Q', 'label': '5R8Q' }, { 'value': '6U66', 'label': '6U66' }, { 'value': '1MQ8', 'label': '1MQ8' }, { 'value': '6CM4', 'label': '6CM4' }, { 'value': '6DLO', 'label': '6DLO' }, { 'value': '3CXD', 'label': '3CXD' }, { 'value': '1U5B', 'label': '1U5B' }, { 'value': '1CK7', 'label': '1CK7' }, { 'value': '2A2R', 'label': '2A2R' }, { 'value': '4JPS', 'label': '4JPS' }, { 'value': '1BND', 'label': '1BND' }, { 'value': '3CBC', 'label': '3CBC' }, { 'value': '5EDM', 'label': '5EDM' }, { 'value': '4P7A', 'label': '4P7A' }, { 'value': '3V96', 'label': '3V96' }, { 'value': '1UUH', 'label': '1UUH' }, { 'value': '6CIK', 'label': '6CIK' }, { 'value': '2QFA', 'label': '2QFA' }, { 'value': '4D1P', 'label': '4D1P' }, { 'value': '6DK5', 'label': '6DK5' }, { 'value': '3K2S', 'label': '3K2S' }, { 'value': '6FCX', 'label': '6FCX' }, { 'value': '3GAX', 'label': '3GAX' }, { 'value': '4ELJ', 'label': '4ELJ' }, { 'value': '4FOC', 'label': '4FOC' }, { 'value': '5D7F', 'label': '5D7F' }, { 'value': '5FO8', 'label': '5FO8' }, { 'value': '1AX8', 'label': '1AX8' }, { 'value': '1I4D', 'label': '1I4D' }, { 'value': '1EG4', 'label': '1EG4' }, { 'value': '6DV5', 'label': '6DV5' }, { 'value': '2VXT', 'label': '2VXT' }, { 'value': '3N56', 'label': '3N56' }, { 'value': '1IE9', 'label': '1IE9' }, { 'value': '1A6Z', 'label': '1A6Z' }, { 'value': '4WJG', 'label': '4WJG' }, { 'value': '1NQL', 'label': '1NQL' }, { 'value': '3HNG', 'label': '3HNG' }, { 'value': '4DUR', 'label': '4DUR' }, { 'value': '6EHA', 'label': '6EHA' }, { 'value': '3T7U', 'label': '3T7U' }, { 'value': '4FM9', 'label': '4FM9' }, { 'value': '2VNT', 'label': '2VNT' }, { 'value': '6WIO', 'label': '6WIO' }, { 'value': '6YG9', 'label': '6YG9' }, { 'value': '1RY7', 'label': '1RY7' }, { 'value': '6BMT', 'label': '6BMT' }, { 'value': '3UF1', 'label': '3UF1' }, { 'value': '6VGE', 'label': '6VGE' }, { 'value': '2MJV', 'label': '2MJV' }, { 'value': '4CFR', 'label': '4CFR' }, { 'value': '1YWH', 'label': '1YWH' }, { 'value': '4JNW', 'label': '4JNW' }, { 'value': '1O7Z', 'label': '1O7Z' }, { 'value': '4YZF', 'label': '4YZF' }, { 'value': '6A70', 'label': '6A70' }, { 'value': '1VCA', 'label': '1VCA' }, { 'value': '1BR9', 'label': '1BR9' }, { 'value': '3TBG', 'label': '3TBG' }, { 'value': '5K31', 'label': '5K31' }, { 'value': '5VCC', 'label': '5VCC' }, { 'value': '1GIF', 'label': '1GIF' }, { 'value': '4U0Q', 'label': '4U0Q' }, { 'value': '1HJX', 'label': '1HJX' }, { 'value': '3URF', 'label': '3URF' }, { 'value': '2JYE', 'label': '2JYE' }, { 'value': '3QRF', 'label': '3QRF' }, { 'value': '3H0T', 'label': '3H0T' }, { 'value': '6V6Q', 'label': '6V6Q' },
  { 'value': '2OWB', 'label': '2OWB' }, { 'value': '2KZU', 'label': '2KZU' }, { 'value': '5M3Y', 'label': '5M3Y' }, { 'value': '3HY2', 'label': '3HY2' }, { 'value': '4B4L', 'label': '4B4L' }, { 'value': '2EZE', 'label': '2EZE' }, { 'value': '5YJG', 'label': '5YJG' }, { 'value': '3V6O', 'label': '3V6O' }, { 'value': '6UUS', 'label': '6UUS' }, { 'value': '5W21', 'label': '5W21' }, { 'value': '5K5S', 'label': '5K5S' }, { 'value': '5I04', 'label': '5I04' }, { 'value': '4XWX', 'label': '4XWX' }, { 'value': '5DVX', 'label': '5DVX' }, { 'value': '6XTX', 'label': '6XTX' }, { 'value': '6D9H', 'label': '6D9H' }, { 'value': '5F71', 'label': '5F71' }, { 'value': '2.00E+19', 'label': '2.00E+19' }, { 'value': '3MRK', 'label': '3MRK' }, { 'value': '5J1A', 'label': '5J1A' }, { 'value': '2J8B', 'label': '2J8B' }, { 'value': '1MPU', 'label': '1MPU' }, { 'value': '3HRN', 'label': '3HRN' }, { 'value': '6BCR', 'label': '6BCR' }, { 'value': '6SA5', 'label': '6SA5' }, { 'value': '5HLY', 'label': '5HLY' }, { 'value': '5DZO', 'label': '5DZO' }, { 'value': '6W9G', 'label': '6W9G' }, { 'value': '2HI4', 'label': '2HI4' }, { 'value': '1WWW', 'label': '1WWW' }, { 'value': '4U72', 'label': '4U72' }, { 'value': '4EYC', 'label': '4EYC' }, { 'value': '2M0P', 'label': '2M0P' }, { 'value': '5NV6', 'label': '5NV6' }, { 'value': '4CG4', 'label': '4CG4' }, { 'value': '5LG8', 'label': '5LG8' }, { 'value': '3MJG', 'label': '3MJG' }, { 'value': '4NFF', 'label': '4NFF' }, { 'value': '4ASQ', 'label': '4ASQ' }, { 'value': '5NIR', 'label': '5NIR' }, { 'value': '5LA4', 'label': '5LA4' }, { 'value': '5NAY', 'label': '5NAY' }, { 'value': '6U1U', 'label': '6U1U' }, { 'value': '1F8U', 'label': '1F8U' }, { 'value': '3VW7', 'label': '3VW7' }, { 'value': '4ZFG', 'label': '4ZFG' }, { 'value': '3QKG', 'label': '3QKG' }, { 'value': '6SUK', 'label': '6SUK' }, { 'value': '6IGK', 'label': '6IGK' }, { 'value': '5W21', 'label': '5W21' }, { 'value': '6GNN', 'label': '6GNN' }, { 'value': '2LSQ', 'label': '2LSQ' }, { 'value': '3L6X', 'label': '3L6X' }, { 'value': '1RV6', 'label': '1RV6' }, { 'value': '5DYE', 'label': '5DYE' }, {
    'value': '4ZRT', 'label':
      '4ZRT'
  }, { 'value': '4OJ2', 'label': '4OJ2' }, { 'value': '3F8U', 'label': '3F8U' }, { 'value': '5C51', 'label': '5C51' }, { 'value': '5K89', 'label': '5K89' }, { 'value': '5VAQ', 'label': '5VAQ' }, { 'value': '1BNL', 'label': '1BNL' }, { 'value': '1US0', 'label': '1US0' }, { 'value': '1BZS', 'label': '1BZS' }, { 'value': '2CDW', 'label': '2CDW' }, { 'value': '4GRW', 'label': '4GRW' }, { 'value': '6YUP', 'label': '6YUP' }, { 'value': '6FKQ', 'label': '6FKQ' }, { 'value': '4ENZ', 'label': '4ENZ' }, { 'value': '3KQ4', 'label': '3KQ4' }, { 'value': '2LNT', 'label': '2LNT' }, { 'value': '1MGS', 'label': '1MGS' }, { 'value': '6NI2', 'label': '6NI2' }, { 'value': '2FDV', 'label': '2FDV' }, { 'value': '5R61', 'label': '5R61' }, { 'value': '5I96', 'label': '5I96' }, { 'value': '3QJ4', 'label': '3QJ4' }, {
    'value':
      '1SMO', 'label': '1SMO'
  }, { 'value': '3ONA', 'label': '3ONA' }, { 'value': '3HG3', 'label': '3HG3' }, { 'value': '2QTL', 'label': '2QTL' }, { 'value': '3QFC', 'label': '3QFC' }, { 'value': '3NKS', 'label': '3NKS' }, { 'value': '1J8C', 'label': '1J8C' }, { 'value': '2JX3', 'label': '2JX3' }, { 'value': '2K27', 'label': '2K27' }, { 'value': '6V1C', 'label': '6V1C' }, { 'value': '6V1D', 'label': '6V1D' }, { 'value': '1T80', 'label': '1T80' }, { 'value': '2PSN', 'label': '2PSN' }, { 'value': '7AAK', 'label': '7AAK' }, { 'value': '6UMX', 'label': '6UMX' }, { 'value': '2V5O', 'label': '2V5O' }, { 'value': '2DOB', 'label': '2DOB' }, {
    'value': '6KXW',
    'label': '6KXW'
  }, { 'value': '6QJA', 'label': '6QJA' }, { 'value': '4AY9', 'label': '4AY9' }, { 'value': '3Q18', 'label': '3Q18' }, { 'value': '6MP4', 'label': '6MP4' }, { 'value': '4HT1', 'label': '4HT1' }, { 'value': '1FG9', 'label': '1FG9' }, { 'value': '6VAX', 'label': '6VAX' }, { 'value': '2E1Q', 'label': '2E1Q' }, { 'value': '1I8L', 'label': '1I8L' }, { 'value': '5A2F', 'label': '5A2F' }, { 'value': '2MGS', 'label': '2MGS' }, { 'value': '1EYB', 'label': '1EYB' }, { 'value': '5OEO', 'label': '5OEO' }, { 'value': '6IAA', 'label': '6IAA' }, { 'value': '4N3A', 'label': '4N3A' }, { 'value': '2YG2', 'label': '2YG2' }, { 'value': '1QDD', 'label': '1QDD' }, { 'value': '1IBX', 'label': '1IBX' }, { 'value': '3KQ0', 'label': '3KQ0' }, { 'value': '6WTH', 'label': '6WTH' }, { 'value': '5PZR', 'label': '5PZR' }, { 'value': '4BQA', 'label': '4BQA' }, { 'value': '1NHL', 'label': '1NHL' }, { 'value': '1XO5', 'label': '1XO5' }, { 'value': '1R3S', 'label': '1R3S' }, { 'value': '4GNB', 'label': '4GNB' }, { 'value': '1AII', 'label': '1AII' }, { 'value': '1GQV', 'label': '1GQV' }, { 'value': '2VIG', 'label': '2VIG' }, { 'value': '1IOX', 'label': '1IOX' }, { 'value': '3SOM', 'label': '3SOM' }, { 'value': '2W8N', 'label': '2W8N' }, { 'value': '1Q7L', 'label': '1Q7L' }, { 'value': '1WYM', 'label': '1WYM' }, { 'value': '3WOY', 'label': '3WOY' }, { 'value': '1K62', 'label': '1K62' }, { 'value': '2VR2', 'label': '2VR2' }, { 'value': '6JBJ', 'label': '6JBJ' }, { 'value': '3S5O', 'label': '3S5O' }, { 'value': '3N93', 'label': '3N93' }, { 'value': '2BOA', 'label': '2BOA' }, { 'value': '3HD6', 'label': '3HD6' }, { 'value': '5CV0', 'label': '5CV0' }, { 'value': '6KHS', 'label': '6KHS' }, { 'value': '1AXC', 'label': '1AXC' }, { 'value': '5J28', 'label': '5J28' }, { 'value': '5UQ3', 'label': '5UQ3' }, { 'value': '2D85', 'label': '2D85' }, { 'value': '4H6J', 'label': '4H6J' }, { 'value': '3DZY', 'label': '3DZY' }, { 'value': '4UAI', 'label': '4UAI' }, { 'value': '6MFA', 'label': '6MFA' }, { 'value': '1H9D', 'label': '1H9D' }, { 'value': '6Q21', 'label': '6Q21' }, { 'value': '4RM8', 'label': '4RM8' }, { 'value': '6ZIO', 'label': '6ZIO' }, { 'value': '5NPV', 'label': '5NPV' }, { 'value': '4RA4', 'label': '4RA4' }, { 'value': '3K6S', 'label': '3K6S' }, { 'value': '6TXQ', 'label': '6TXQ' }, { 'value': '2G4B', 'label': '2G4B' }, { 'value': '3KTR', 'label': '3KTR' }, { 'value': '5IQZ', 'label': '5IQZ' }, { 'value': '4L1M', 'label': '4L1M' }, { 'value': '2Z7F', 'label': '2Z7F' }, { 'value': '1AOA', 'label': '1AOA' }, { 'value': '1UEL', 'label': '1UEL' }, { 'value': '3P0U', 'label': '3P0U' }, { 'value': '2FZP', 'label': '2FZP' }, { 'value': '2D58', 'label': '2D58' }, { 'value': '3S9G', 'label': '3S9G' }, { 'value': '5VDC', 'label': '5VDC' }, { 'value': '2UYY', 'label': '2UYY' }, { 'value': '6H02', 'label': '6H02' }, { 'value': '3FMP', 'label': '3FMP' }, { 'value': '6PSE', 'label': '6PSE' }, { 'value': '3C5V', 'label': '3C5V' },
  { 'value': '1UPQ', 'label': '1UPQ' }, { 'value': '3KCG', 'label': '3KCG' }]
const PDBIds = (props) => {
    const [genes, setGenes] = React.useState([{ 'value': '1NFN', 'label': '1NFN' }, { 'value': '4ZT1', 'label': '4ZT1' }, { 'value': '6I7U', 'label': '6I7U' }, { 'value': '5MXA', 'label': '5MXA' }, {
        'value':
          '1KXP', 'label': '1KXP'
      }, { 'value': '3V83', 'label': '3V83' }, { 'value': '2GD4', 'label': '2GD4' }, { 'value': '4IP8', 'label': '4IP8' }, { 'value': '6O5E', 'label': '6O5E' }, { 'value': '1QMN', 'label': '1QMN' }, { 'value': '1FLE', 'label': '1FLE' }, { 'value': '6SAZ', 'label': '6SAZ' }, { 'value': '1ALU', 'label': '1ALU' }, { 'value': '4CSK', 'label': '4CSK' }, { 'value': '3KFD', 'label': '3KFD' }, { 'value': '2BIP', 'label': '2BIP' }, { 'value': '4AWN', 'label': '4AWN' }, { 'value': '1L6J', 'label': '1L6J' }, { 'value': '5XWD', 'label': '5XWD' }, { 'value': '1BI7', 'label': '1BI7' }, { 'value': '6N2U', 'label': '6N2U' }, {
        'value': '5UGW',
        'label': '5UGW'
      }, { 'value': '4GLN', 'label': '4GLN' }, { 'value': '3PVN', 'label': '3PVN' }, { 'value': '6GOD', 'label': '6GOD' }, { 'value': '1DOK', 'label': '1DOK' }, { 'value': '6V4U', 'label': '6V4U' }, { 'value': '2ZCH', 'label': '2ZCH' }, { 'value': '5VAU', 'label': '5VAU' }, { 'value': '5C9C', 'label': '5C9C' }, { 'value': '5R8Q', 'label': '5R8Q' }, { 'value': '6U66', 'label': '6U66' }, { 'value': '1MQ8', 'label': '1MQ8' }, { 'value': '6CM4', 'label': '6CM4' }, { 'value': '6DLO', 'label': '6DLO' }, { 'value': '3CXD', 'label': '3CXD' }, { 'value': '1U5B', 'label': '1U5B' }, { 'value': '1CK7', 'label': '1CK7' }, { 'value': '2A2R', 'label': '2A2R' }, { 'value': '4JPS', 'label': '4JPS' }, { 'value': '1BND', 'label': '1BND' }, { 'value': '3CBC', 'label': '3CBC' }, { 'value': '5EDM', 'label': '5EDM' }, { 'value': '4P7A', 'label': '4P7A' }, { 'value': '3V96', 'label': '3V96' }, { 'value': '1UUH', 'label': '1UUH' }, { 'value': '6CIK', 'label': '6CIK' }, { 'value': '2QFA', 'label': '2QFA' }, { 'value': '4D1P', 'label': '4D1P' }, { 'value': '6DK5', 'label': '6DK5' }, { 'value': '3K2S', 'label': '3K2S' }, { 'value': '6FCX', 'label': '6FCX' }, { 'value': '3GAX', 'label': '3GAX' }, { 'value': '4ELJ', 'label': '4ELJ' }, { 'value': '4FOC', 'label': '4FOC' }, { 'value': '5D7F', 'label': '5D7F' }, { 'value': '5FO8', 'label': '5FO8' }, { 'value': '1AX8', 'label': '1AX8' }, { 'value': '1I4D', 'label': '1I4D' }, { 'value': '1EG4', 'label': '1EG4' }, { 'value': '6DV5', 'label': '6DV5' }, { 'value': '2VXT', 'label': '2VXT' }, { 'value': '3N56', 'label': '3N56' }, { 'value': '1IE9', 'label': '1IE9' }, { 'value': '1A6Z', 'label': '1A6Z' }, { 'value': '4WJG', 'label': '4WJG' }, { 'value': '1NQL', 'label': '1NQL' }, { 'value': '3HNG', 'label': '3HNG' }, { 'value': '4DUR', 'label': '4DUR' }, { 'value': '6EHA', 'label': '6EHA' }, { 'value': '3T7U', 'label': '3T7U' }, { 'value': '4FM9', 'label': '4FM9' }, { 'value': '2VNT', 'label': '2VNT' }, { 'value': '6WIO', 'label': '6WIO' }, { 'value': '6YG9', 'label': '6YG9' }, { 'value': '1RY7', 'label': '1RY7' }, { 'value': '6BMT', 'label': '6BMT' }, { 'value': '3UF1', 'label': '3UF1' }, { 'value': '6VGE', 'label': '6VGE' }, { 'value': '2MJV', 'label': '2MJV' }, { 'value': '4CFR', 'label': '4CFR' }, { 'value': '1YWH', 'label': '1YWH' }, { 'value': '4JNW', 'label': '4JNW' }, { 'value': '1O7Z', 'label': '1O7Z' }, { 'value': '4YZF', 'label': '4YZF' }, { 'value': '6A70', 'label': '6A70' }, { 'value': '1VCA', 'label': '1VCA' }, { 'value': '1BR9', 'label': '1BR9' }, { 'value': '3TBG', 'label': '3TBG' }, { 'value': '5K31', 'label': '5K31' }, { 'value': '5VCC', 'label': '5VCC' }, { 'value': '1GIF', 'label': '1GIF' }, { 'value': '4U0Q', 'label': '4U0Q' }, { 'value': '1HJX', 'label': '1HJX' }, { 'value': '3URF', 'label': '3URF' }, { 'value': '2JYE', 'label': '2JYE' }, { 'value': '3QRF', 'label': '3QRF' }, { 'value': '3H0T', 'label': '3H0T' }, { 'value': '6V6Q', 'label': '6V6Q' },
      { 'value': '2OWB', 'label': '2OWB' }, { 'value': '2KZU', 'label': '2KZU' }, { 'value': '5M3Y', 'label': '5M3Y' }, { 'value': '3HY2', 'label': '3HY2' }, { 'value': '4B4L', 'label': '4B4L' }, { 'value': '2EZE', 'label': '2EZE' }, { 'value': '5YJG', 'label': '5YJG' }, { 'value': '3V6O', 'label': '3V6O' }, { 'value': '6UUS', 'label': '6UUS' }, { 'value': '5W21', 'label': '5W21' }, { 'value': '5K5S', 'label': '5K5S' }, { 'value': '5I04', 'label': '5I04' }, { 'value': '4XWX', 'label': '4XWX' }, { 'value': '5DVX', 'label': '5DVX' }, { 'value': '6XTX', 'label': '6XTX' }, { 'value': '6D9H', 'label': '6D9H' }, { 'value': '5F71', 'label': '5F71' }, { 'value': '2.00E+19', 'label': '2.00E+19' }, { 'value': '3MRK', 'label': '3MRK' }, { 'value': '5J1A', 'label': '5J1A' }, { 'value': '2J8B', 'label': '2J8B' }, { 'value': '1MPU', 'label': '1MPU' }, { 'value': '3HRN', 'label': '3HRN' }, { 'value': '6BCR', 'label': '6BCR' }, { 'value': '6SA5', 'label': '6SA5' }, { 'value': '5HLY', 'label': '5HLY' }, { 'value': '5DZO', 'label': '5DZO' }, { 'value': '6W9G', 'label': '6W9G' }, { 'value': '2HI4', 'label': '2HI4' }, { 'value': '1WWW', 'label': '1WWW' }, { 'value': '4U72', 'label': '4U72' }, { 'value': '4EYC', 'label': '4EYC' }, { 'value': '2M0P', 'label': '2M0P' }, { 'value': '5NV6', 'label': '5NV6' }, { 'value': '4CG4', 'label': '4CG4' }, { 'value': '5LG8', 'label': '5LG8' }, { 'value': '3MJG', 'label': '3MJG' }, { 'value': '4NFF', 'label': '4NFF' }, { 'value': '4ASQ', 'label': '4ASQ' }, { 'value': '5NIR', 'label': '5NIR' }, { 'value': '5LA4', 'label': '5LA4' }, { 'value': '5NAY', 'label': '5NAY' }, { 'value': '6U1U', 'label': '6U1U' }, { 'value': '1F8U', 'label': '1F8U' }, { 'value': '3VW7', 'label': '3VW7' }, { 'value': '4ZFG', 'label': '4ZFG' }, { 'value': '3QKG', 'label': '3QKG' }, { 'value': '6SUK', 'label': '6SUK' }, { 'value': '6IGK', 'label': '6IGK' }, { 'value': '5W21', 'label': '5W21' }, { 'value': '6GNN', 'label': '6GNN' }, { 'value': '2LSQ', 'label': '2LSQ' }, { 'value': '3L6X', 'label': '3L6X' }, { 'value': '1RV6', 'label': '1RV6' }, { 'value': '5DYE', 'label': '5DYE' }, {
        'value': '4ZRT', 'label':
          '4ZRT'
      }, { 'value': '4OJ2', 'label': '4OJ2' }, { 'value': '3F8U', 'label': '3F8U' }, { 'value': '5C51', 'label': '5C51' }, { 'value': '5K89', 'label': '5K89' }, { 'value': '5VAQ', 'label': '5VAQ' }, { 'value': '1BNL', 'label': '1BNL' }, { 'value': '1US0', 'label': '1US0' }, { 'value': '1BZS', 'label': '1BZS' }, { 'value': '2CDW', 'label': '2CDW' }, { 'value': '4GRW', 'label': '4GRW' }, { 'value': '6YUP', 'label': '6YUP' }, { 'value': '6FKQ', 'label': '6FKQ' }, { 'value': '4ENZ', 'label': '4ENZ' }, { 'value': '3KQ4', 'label': '3KQ4' }, { 'value': '2LNT', 'label': '2LNT' }, { 'value': '1MGS', 'label': '1MGS' }, { 'value': '6NI2', 'label': '6NI2' }, { 'value': '2FDV', 'label': '2FDV' }, { 'value': '5R61', 'label': '5R61' }, { 'value': '5I96', 'label': '5I96' }, { 'value': '3QJ4', 'label': '3QJ4' }, {
        'value':
          '1SMO', 'label': '1SMO'
      }, { 'value': '3ONA', 'label': '3ONA' }, { 'value': '3HG3', 'label': '3HG3' }, { 'value': '2QTL', 'label': '2QTL' }, { 'value': '3QFC', 'label': '3QFC' }, { 'value': '3NKS', 'label': '3NKS' }, { 'value': '1J8C', 'label': '1J8C' }, { 'value': '2JX3', 'label': '2JX3' }, { 'value': '2K27', 'label': '2K27' }, { 'value': '6V1C', 'label': '6V1C' }, { 'value': '6V1D', 'label': '6V1D' }, { 'value': '1T80', 'label': '1T80' }, { 'value': '2PSN', 'label': '2PSN' }, { 'value': '7AAK', 'label': '7AAK' }, { 'value': '6UMX', 'label': '6UMX' }, { 'value': '2V5O', 'label': '2V5O' }, { 'value': '2DOB', 'label': '2DOB' }, {
        'value': '6KXW',
        'label': '6KXW'
      }, { 'value': '6QJA', 'label': '6QJA' }, { 'value': '4AY9', 'label': '4AY9' }, { 'value': '3Q18', 'label': '3Q18' }, { 'value': '6MP4', 'label': '6MP4' }, { 'value': '4HT1', 'label': '4HT1' }, { 'value': '1FG9', 'label': '1FG9' }, { 'value': '6VAX', 'label': '6VAX' }, { 'value': '2E1Q', 'label': '2E1Q' }, { 'value': '1I8L', 'label': '1I8L' }, { 'value': '5A2F', 'label': '5A2F' }, { 'value': '2MGS', 'label': '2MGS' }, { 'value': '1EYB', 'label': '1EYB' }, { 'value': '5OEO', 'label': '5OEO' }, { 'value': '6IAA', 'label': '6IAA' }, { 'value': '4N3A', 'label': '4N3A' }, { 'value': '2YG2', 'label': '2YG2' }, { 'value': '1QDD', 'label': '1QDD' }, { 'value': '1IBX', 'label': '1IBX' }, { 'value': '3KQ0', 'label': '3KQ0' }, { 'value': '6WTH', 'label': '6WTH' }, { 'value': '5PZR', 'label': '5PZR' }, { 'value': '4BQA', 'label': '4BQA' }, { 'value': '1NHL', 'label': '1NHL' }, { 'value': '1XO5', 'label': '1XO5' }, { 'value': '1R3S', 'label': '1R3S' }, { 'value': '4GNB', 'label': '4GNB' }, { 'value': '1AII', 'label': '1AII' }, { 'value': '1GQV', 'label': '1GQV' }, { 'value': '2VIG', 'label': '2VIG' }, { 'value': '1IOX', 'label': '1IOX' }, { 'value': '3SOM', 'label': '3SOM' }, { 'value': '2W8N', 'label': '2W8N' }, { 'value': '1Q7L', 'label': '1Q7L' }, { 'value': '1WYM', 'label': '1WYM' }, { 'value': '3WOY', 'label': '3WOY' }, { 'value': '1K62', 'label': '1K62' }, { 'value': '2VR2', 'label': '2VR2' }, { 'value': '6JBJ', 'label': '6JBJ' }, { 'value': '3S5O', 'label': '3S5O' }, { 'value': '3N93', 'label': '3N93' }, { 'value': '2BOA', 'label': '2BOA' }, { 'value': '3HD6', 'label': '3HD6' }, { 'value': '5CV0', 'label': '5CV0' }, { 'value': '6KHS', 'label': '6KHS' }, { 'value': '1AXC', 'label': '1AXC' }, { 'value': '5J28', 'label': '5J28' }, { 'value': '5UQ3', 'label': '5UQ3' }, { 'value': '2D85', 'label': '2D85' }, { 'value': '4H6J', 'label': '4H6J' }, { 'value': '3DZY', 'label': '3DZY' }, { 'value': '4UAI', 'label': '4UAI' }, { 'value': '6MFA', 'label': '6MFA' }, { 'value': '1H9D', 'label': '1H9D' }, { 'value': '6Q21', 'label': '6Q21' }, { 'value': '4RM8', 'label': '4RM8' }, { 'value': '6ZIO', 'label': '6ZIO' }, { 'value': '5NPV', 'label': '5NPV' }, { 'value': '4RA4', 'label': '4RA4' }, { 'value': '3K6S', 'label': '3K6S' }, { 'value': '6TXQ', 'label': '6TXQ' }, { 'value': '2G4B', 'label': '2G4B' }, { 'value': '3KTR', 'label': '3KTR' }, { 'value': '5IQZ', 'label': '5IQZ' }, { 'value': '4L1M', 'label': '4L1M' }, { 'value': '2Z7F', 'label': '2Z7F' }, { 'value': '1AOA', 'label': '1AOA' }, { 'value': '1UEL', 'label': '1UEL' }, { 'value': '3P0U', 'label': '3P0U' }, { 'value': '2FZP', 'label': '2FZP' }, { 'value': '2D58', 'label': '2D58' }, { 'value': '3S9G', 'label': '3S9G' }, { 'value': '5VDC', 'label': '5VDC' }, { 'value': '2UYY', 'label': '2UYY' }, { 'value': '6H02', 'label': '6H02' }, { 'value': '3FMP', 'label': '3FMP' }, { 'value': '6PSE', 'label': '6PSE' }, { 'value': '3C5V', 'label': '3C5V' },
      { 'value': '1UPQ', 'label': '1UPQ' }, { 'value': '3KCG', 'label': '3KCG' }])
    return (
        <div className="py-4">
            <label style={{ color: 'black' }}>Search: <input type="text" onChange={(e) => { console.log(genes); e.target.value.length == 0 ? setGenes(genesOriginal) :setGenes(genes.filter((gene) => gene.value.startsWith(e.target.value) && e.target.value != 0)) }}></input></label>
            <Table striped bordered hover>
                <tbody>
                    <tr>
                        <th>PDB ID</th>
                    </tr>
                    {genes.map(item => <tr key={item.label}>
                        {item.value}
                    </tr>)}

                </tbody>
            </Table>
        </div>
    );
};
export default PDBIds;
